name: "fabric"
nodes:
  #peer0.org1.example.com
  - 0.0.0.0:7051
  #peer1.org1.example.com
  - 0.0.0.0:8051
  #peer0.org2.example.com
  - 0.0.0.0:9051
  #peer1.org2.example.com
  - 0.0.0.0:10051
extra:
  - label: "appUser"
    mspID: "Org2MSP"
    cert: |
      -----BEGIN CERTIFICATE-----
      MIICKTCCAdCgAwIBAgIQKQFz4ksKPeII9yCTVJlAVjAKBggqhkjOPQQDAjBzMQsw
      CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
      YW5jaXNjbzEZMBcGA1UEChMQb3JnMi5leGFtcGxlLmNvbTEcMBoGA1UEAxMTY2Eu
      b3JnMi5leGFtcGxlLmNvbTAeFw0yMDEwMzEyMDE3MDBaFw0zMDEwMjkyMDE3MDBa
      MGwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1T
      YW4gRnJhbmNpc2NvMQ8wDQYDVQQLEwZjbGllbnQxHzAdBgNVBAMMFlVzZXIxQG9y
      ZzIuZXhhbXBsZS5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASbIq/YUCOe
      ApLQA3uL6ca/FvcrIIwe6soO8TcS0kqbhU4bK2scS2UX8QiyTSL6AaIUxOx/GhVP
      yIfkoVdCbbA5o00wSzAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIwADArBgNV
      HSMEJDAigCDw5b1Wx1qkJz3H3pCiHrbpA94/AGBJGZ2hVlg7Mv3gtzAKBggqhkjO
      PQQDAgNHADBEAiB/V1dL62bdd2xOSDT0S5nShu8QiF5oqQXTp92z649AdQIgCFw1
      FU5B1xtVXNmuf74VO1ZdLZP7wt+YH8I3zxInqk8=
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg35z/sLNihPfvKq27
      qtsJm6lRLVsU+Y/GLFgOma9rv76hRANCAASbIq/YUCOeApLQA3uL6ca/FvcrIIwe
      6soO8TcS0kqbhU4bK2scS2UX8QiyTSL6AaIUxOx/GhVPyIfkoVdCbbA5
      -----END PRIVATE KEY-----
    ccpPath: "localImplementation/artifacts/channel/crypto-config/peerOrganizations/org2.example.com/connection-org2.yaml"
    localHost: "true"
    channelName: "mychannel"
    contractName: "aviation"


